package berkbot_puns

import (
	"math/rand"

	"github.com/bwmarrin/discordgo"
)

var puns = []string{
	"A man died today when a pile of books fell on him. He only had his shelf to blame.",
	"Thanks for explaining the word 'many' to me, it means alot.",
	"My room mates are concerned that I'm using their kitchen utensils, but that's a whisk i'm willing to take.",
	"My friend told me ten puns to try to make me laugh. No pun intended.",
	"When I get naked in the bathroom, the shower usually gets turned on.",
	"A criminals best asset is his lie ability.",
	"Weight loss pills stolen this morning - police say suspects are still at large.",
	"Today a man knocked on my door and asked for a small donation towards the local swimming pool, so I gave him a glass of water.",
	"Stop with the blind jokes...I dont see the point.",
	"Two antennas met on a roof, fell in love and got married. The ceremony wasn't much, but the reception was excellent.",
	"If at first you don't succeed then skydiving is not for you.",
	"It's not that the man didn't know how to juggle, he just didn't have the balls to do it.",
	"She didn't marry the gardener. Too rough around the hedges.",
	"A boiled egg in the morning is hard to beat.",
	"There's a new type of broom out, it's sweeping the nation.",
	"Americans prefer houses with basements. In fact, they're best cellars!",
	"She had a photographic memory but never developed it.",
	"How do you organize a space party? You planet!",
	"I put up a high-voltage electric fence around my property over the weekend, my neighbour is dead against it...",
	"For a fungi to grow you must give it as mushroom as possible.",
	"I hate carrying my luggage around the airport, I rest my case.",
	"If a judge loves the sound of his own  voice, expect a long sentence.",
	"It was a terrible summer for Humpty Dumpty... but he had a great fall.",
	"This girl said she recognized me from the vegetarian club. But I've never met herbivore!",
	"I'm reading a book about anti-gravity. It's impossible to put down!",
	"I used to date a girl with a lazy eye. It turns out she was seeing someone else the whole time!",
	"What is Forest Gump's facebook password? 1forest1",
	"When he proposed to her, she found it very engaging.",
	"An expensive laxative will give you a run for your money.",
	"How do construction workers party? They raise the roof.",
	"A dog gave birth to puppies near the road and was ticketed for littering.",
	"Why do they put fences around cementeries? Because people are dying to get in!",
	"Did you hear about the kid napping? He woke up.",
	"My wife tried to apply at the post office but they wouldn't letter. They said only mails work here.",
	"I wrote a song for a tortilla. Well, its more of a wrap.",
	"Did you hear about the man who lost his left side? He's all right now.",
	"Two peanuts walk into a bar and one was a salted.",
	"He wears glasses during math because it improves division.",
	"A rubber band slingshot was confiscated in algebra class for being a weapon of math disruption.",
	"He didn't tell his mother that he ate some glue. His lips were sealed.",
	"I used to be a doctor, but then I lost patients.",
	"Ed has no girlfriend because Sheeran away.",
	"How did I escape Iraq? Iran.",
	"I make apocalypse jokes like there's no tomorrow.",
	"I used to be a shoe salesman until they gave me the boot.",
	"Why are teddy bears never hungry? They are always stuffed!",
	"Cartoonist found dead in home. Details are sketchy.",
	"When I asked my dog how his day was he said it was rough.",
	"The best way to communicate with fish is to drop them a line",
	"I should have been sad when my flash light batteries died, but I was delighted.",
	"Be kind to your dentist because he has fillings too.",
	"I removed the shell from my racing snail to make it go faster - but it just made it more sluggish.",
	"My grandma told me her joints are getting weaker, so I told her to roll them tighter.",
	"Life as a yo-yo has its ups and downs.",
	"Man, choking on sugar seems like the sweetest way to die!",
	"I don't trust stairs... they are always up to something.",
	"My wife told me to stop speaking in numbers. But I didn't 1 2.",
	"The painter was hospitalized due to too many strokes.",
	"I've been thinking about learning Braille, but its a bit of a touchy subject.",
	"Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
	"A bicycle can't stand on its own because it is two-tired.",
	"What happens when a sheep, a drum and a snake fall from a cliff BA DUM TS.",
	"I tripped over my girlfriends bra, seemed to be a booby trap.",
	"My new diet consists of aircraft, however its a bit plane.",
	"It was an emotional wedding. Even the cake was in tiers.",
	"I've got a chicken-proof front lawn. It's impeccable!",
	"Shout out to people who don't know what the opposite of in is!",
	"What's a cow eating grass? A lawn mooer.",
	"I use to hate facial hair. But then it grew on me!",
	"Cows lie down in the rain to keep each udder dry.",
	"The shovel was a ground-breaking invention.",
	"I asked a Frenchman if he played video games, he said wii.",
	"Go to Italy, Rome around and pasta time.",
	"By shear coincidence, all these sheep look the same.",
	"If you've been thinking about singing karaoke with a friend, just duet!",
	"I did a theatrical performance about puns. It was a play on words.",
	"You didn’t hear about the three big holes in the ground? Well, well, well.",
	"I couldn't figure out how to put my seatbelt on, but then it clicked.",
	"It's true I don't like soap, but you don't have to rub it in my face!",
	"I saw a beaver movie last night, it was the best dam movie ever.",
	"My grandma is on speed dial and now I call her instagram.",
	"Two wrongs can make a riot.",
	"I went to buy some camouflage trousers the other day, but I couldn't find any.",
	"Did you hear about the Italian chef with a terminal illness? He pastaway.",
	"I'm going to buy some velcro for my shoes instead of laces. Why knot?",
	"The butcher walked backwards into the meat grinder and got a little behind in his work.",
	"A jumper cable walks into a bar. The bartender says, I'll serve  you, but don't start anything",
	"What do you call a dinosaur with an extensive vocabulary? A Thesaurus.",
	"Tight leather jackets are hard to pull off.",
	"I got a reversible jacket for Christmas, I can't wait to see how it turns out.",
	"After the birth of your first child, your role in life will become apparent.",
	"I use to be a baby but I grew out of it.",
	"I was addicted to soap... I'm clean now.",
	"I used to be a banker, but I lost interest.",
	"Jokes with punch lines can be painfully funny.",
	"He drove his expensive car into a tree and found out how the Mercedes bends.",
	"I don't think I need a spine. It's holding me back.",
	"I wanted to be an astronaut when I was a kid but my parents told me the sky was the limit.",
	"Pun of the day is very important. As seven days without a pun makes one weak.",
	"It's raining cats and dogs out there. I know, I just stepped in a poodle.",
	"Light travels faster than sound. That's why some people appear bright until you hear them speak",
	"I was wondering why the ball was getting bigger. Then it hit me",
	"I have a few jokes about unemployed people, but none of them work",
	"\"I have a split personality,\" said Tom, being frank.",
	"How do you make holy water? You boil the hell out of it",
	"When life gives you melons, you're dyslexic",
	"I Renamed my iPod The Titanic, so when I plug it in, it says “The Titanic is syncing.”",
	"Will glass coffins be a success? Remains to be seen",
	"It's hard to explain puns to kleptomaniacs because they always take things literally",
	"Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta sea",
	"I lost my job at the bank on my very first day. A woman asked me to check her balance, so I pushed her over",
	"What’s the difference between a hippo and a zippo? One is really heavy and the other is a little lighter",
	"Two windmills are standing in a wind farm. One asks, “What’s your favorite kind of music?” The other says, “I’m a big metal fan.”",
	"Did you hear about the guy whose whole left side was cut off? He’s all right now",
	"The man who survived pepper spray and mustard gas is now a seasoned veteran",
	"I can’t believe I got fired from the calendar factory. All I did was take a day off",
	"My dad farted in an elevator, it was wrong on so many levels",
	"What do you call a bee that can’t make up its mind? A maybe",
	"I went to buy some camouflage trousers yesterday but couldn't find any",
	"I tried to sue the airline for losing my luggage. I lost my case",
	"Hear about the new restaurant called Karma? There’s no menu - you get what you deserve",
	"England doesn't have a kidney bank, but it does have a Liverpool",
	"All chemists know that alcohol is always a solution",
	"Jill broke her finger today, but on the other hand she was completely fine",
	"A police officer just knocked on my door and told me my dogs are chasing people on bikes. That’s ridiculous. My dogs don’t even own bikes",
	"She had a photographic memory but never developed it",
	"When everything is coming your way, you're in the wrong lane",
	"The furniture store keeps calling me to come back. But all I wanted was one night stand",
	"A cross-eyed teacher couldn’t control his pupils",
	"When the past, present, and future go camping they always argue. It's intense tense in tents",
	"A mean crook going down stairs = A condescending con, descending",
	"What did the janitor say when he jumped out of the closet? SUPPLIES!",
	"Is it ignorance or apathy that's destroying the world today? I don't know and don't really care",
	"Let me tell you about my grandfather. He was a good man, a brave man. He had the heart of a lion, and a lifetime ban from the zoo",
	"My dad, unfortunately, passed away when we couldn’t remember his blood type… His last words to us were, “Be positive!”",
	"What do you call the wife of a hippie? A Mississippi",
	"Which country’s capital has the fastest-growing population? Ireland. Every day it’s Dublin.",
	"I wasn’t originally going to get a brain transplant, but then I changed my mind",
	"What do you get when you mix alcohol and literature? Tequila mockingbird",
	"There was a kidnapping at school yesterday. Don’t worry, though - he woke up",
	"How do you throw a space party? You planet",
	"How does an attorney sleep? First he lies on one side, then he lies on the other",
	"My ex-wife still misses me. But her aim is starting to improve",
	"What washes up on tiny beaches? Microwaves",
	"Two fish are in a tank, one says to the other \"how do you drive this thing?\"",
	"What are the strongest days of the week? Saturday and Sunday, the rest are weekdays",
	"I was going to make a chemistry joke, but since I'm kinda late to the thread, the good ones argon",
	"What’s the difference between a poorly dressed man on a bicycle and a nicely dressed man on a tricycle? A tire",
	"I hate how funerals are always at 9 a.m. I’m not really a mourning person",
	"I saw an ad for burial plots, and I thought: “That’s the last thing I need!”",
	"I don't suffer from insanity. I enjoy every minute of it",
	"The guy who invented the door knocker got a no-bell prize",
	"German sausage jokes are just the wurst",
	"The other day I tried to make a chemistry joke, but got no reaction",
	"What do you call an alligator in a vest? An investigator",
	"Sleeping comes so naturally to me, I could do it with my eyes closed",
	"I used to be indecisive; now I'm not so sure",
	"What do you call the ghost of a chicken? A poultry-geist",
	"Need an ark? I Noah guy",
	"Police were called to a daycare center where a three-year-old was resisting a rest",
	"I walked into my sister's room and tripped on a bra... It was a booby trap",
	"How does Moses make coffee? Hebrews it",
	"He who laughs last thinks slowest",
	"I like European food so I decided to Russia over there because I was Hungary. After Czech'ing the menu I ordered Turkey. When I was Finnished I told the waiter 'Spain good but there is Norway I could eat another bite'",
	"I'm on a seafood diet. Every time I see food, I eat it",
	"Why aren’t dogs good dancers? Because they have two left feet!",
	"What did the grape say when it got stepped on? Nothing - but it let out a little whine",
	"The machine at the coin factory just suddenly stopped working, with no explanation. It doesn’t make any cents",
	"Why are frogs so happy? They eat whatever bugs them",
	"What do you call a man with no arms and no legs stuffed in your mailbox? Bill",
	"What do you call a super articulate dinosaur? A Thesaurus",
	"Why is the number six afraid of seven? Because seven ate nine",
	"What did one flag say to the other? Nothing, it just waved.",
	"Somebody stole all my lamps… I couldn’t be more de-lighted!",
	"How was Rome split in two? With a pair of Ceasars",
	"I lost my mood ring, and I don't know how I'm feeling about that",
	"I bought a boat because it was for sail",
	"I'm not a doctor but I'm losing my patience",
	"Being vegetarian was a huge missed-steak",
	"What would you get if you'd put a lawyer in a suit? A lawsuit",
}

func getRandomPun() string {
	return puns[rand.Intn(len(puns))]
}

func Pun(session *discordgo.Session, message *discordgo.MessageCreate) {
	if message.Author.ID == session.State.User.ID {
		return
	}

	if message.Content == "!pun" {
		session.ChannelMessageSend(message.ChannelID, getRandomPun())
	}
}
